name: Astronomer CI - Create Deployment Preview

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  create_deployment_preview:
    if: contains(github.event.comment.body, '/create')
    runs-on: ubuntu-latest
    steps:
    - name: create
      shell: bash
      run: echo creating deployment
